### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by rs01923**
made most strings use `string.format` for easier message translation support.. if needed
fixed some code not following code line

### CODE REVIEW

**Comment by hopperelec** [comment]
For internationalization, I would use the Chat Component API. `String.format()` helps with readability, but I'm not sure how it helps with translation support?

**Comment by rs01923** [comment]
> For internationalization, I would use the Chat Component API. `String.format()` helps with readability, but I'm not sure how it helps with translation support?

you can port for example "string %s" into a config and the user would be able to adjust the message without issues values, objects etc would still be placed into the message because of "%s", this isn't limited to just translations the user would be able to change the message to whatever

**Comment by hopperelec** [comment]
> you can port for example "string %s" into a config and the user would be able to adjust the message without issues values, objects etc would still be placed into the message because of "%s"

Ah, that's fair. I still think the Chat Component API (specifically Adventure) would be much better suited to this, though (see [PaperMC docs](https://docs.papermc.io/paper/dev/component-api/i18n)). I've never used it before, but it's definitely something I wanted to try

**Comment by rs01923** [comment]
> > you can port for example "string %s" into a config and the user would be able to adjust the message without issues values, objects etc would still be placed into the message because of "%s"
> 
> Ah, that's fair. I still think the Chat Component API (specifically Adventure) would be much better suited to this, though (see [PaperMC docs](https://docs.papermc.io/paper/dev/component-api/i18n)). I've never used it before, but it's definitely something I wanted to try

switched all messages to use the chat component api for any future language/customization support
(i dont use newer server software much tbh i forgot this existed)

**Comment by hopperelec** [comment]
That was very quick, thank you so much!

I think some of the translation keys are a bit confusing; I'm looking to see if there's a naming convention for translation keys to standardize it a bit but I can't seem to find one, sadly.

I'd also like to make the following strings use the same system.
[`"ItemRace Score"`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRacePlugin.java#L54)
[`"Next page"`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceInventoryProvider.java#L32)
[`"Previous page"`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceInventoryProvider.java#L34)
[`player.getName() + "'s ItemRace inventory"`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L156)
[`"ItemRace Leaderboard"`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L164) (this would also require changing the number of `=` on [the ending line](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L187); since Minecraft uses a monospaced font, it will probably be easiest to do this programatically)

The display name for command arguments `@name("<name>")` should also be put in a locale file under the key `acf-core.parameter.<name>` (see [ACF docs](https://github.com/aikar/commands/wiki/Annotations#name))

**Comment by hopperelec** [comment]
Oh, [`material.name()`](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceUtils.java#L9) also needs to be translated, which can be done using [`Material::getTranslationKey`](https://jd.papermc.io/paper/1.21/org/bukkit/Material.html#translationKey())

**Comment by rs01923** [comment]
> That was very quick, thank you so much!
> 
> I think some of the translation keys are a bit confusing; I'm looking to see if there's a naming convention for translation keys to standardize it a bit but I can't seem to find one, sadly.
> 
> I'd also like to make the following strings use the same system. ["ItemRace Score"](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRacePlugin.java#L54) ["Next page"](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceInventoryProvider.java#L32) ["Previous page"](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceInventoryProvider.java#L34) [player.getName() + "'s ItemRace inventory"](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L156) ["ItemRace Leaderboard"](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L164) (this would also require changing the number of `=` on [the ending line](https://github.com/notrhys/ItemRacePlugin/blob/d635ef13571cfdc44b62b33b54d85b5cc572a152/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceCommand.java#L187); since Minecraft uses a monospaced font, it will probably be easiest to do this programatically)
> 
> The display name for command arguments `@name("<name>")` should also be put in a locale file under the key `acf-core.parameter.<name>` (see [ACF docs](https://github.com/aikar/commands/wiki/Annotations#name))

i couldn't find any other words off the top of my head to name them so i just did whatever, feel free to change them

**Comment by hopperelec** [comment]
As I say, I couldn't find a standard, but separating translation keys by commands seems reasonable. If any translation keys are shared between commands, they could be put under a `commands.generic` key

**Comment by hopperelec** [comment]
Turns out I was wrong about the Minecraft font being monospaced which is a bit annoying but oh well

**Comment by hopperelec** [comment]
I've nearly got everything I mentioned working, but I also wanted to move [this](https://github.com/notrhys/ItemRacePlugin/blob/master/src/main/java/uk/co/hopperelec/mc/itemrace/ItemRaceInventoryProvider.java#L53-L54) into a translation key. However, I can't seem to get anything inside `ItemRaceInventoryProvider` working; it just shows the translation key as the name. For example, here is how I did the item names.
```java
itemMeta.itemName(Component.translatable(
        "inventory.itemname",
        Component.translatable(itemStack.getType().translationKey()),
        Component.text(entry.getValue())
));
```

**Comment by hopperelec** [comment]
I need to get some sleep so I'm just gonna push my changes and mark this PR as a draft for the time being. The aforementioned issue still needs to be fixed and command argument names still need to be internationalized.

**Comment by hopperelec** [comment]
Couldn't get the `@Name` translations working and it is only really useful if commands are also documented with `@Description` which is, ironically, not documented itself. HelpCommand is unstable anyways. So, for now I'll just leave them as-is.

**Pull request merged**
